language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

install:
  - pip install -U pip
  - pip --version
  - pip install -U tox tox-travis coveralls

script:
  - tox
  - tox -e coverage

after_success:
  - coveralls

jobs:
  include:
    - env: TOXENV=lint
      script:
        - tox
    - stage: PyPI release
      deploy:
        provider: pypi
        user: "__token__"
        password: "${PYPI_API_TOKEN}"
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          tags: true
