language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

jobs:
  include:
    - env: TOXENV=lint

install:
  - pip install -U pip
  - pip --version
  - pip install -U tox tox-travis

script:
  - tox
